[package]
name = "random_eviction_cache"
authors = ["Xingzhi Andy <xye8@u.rochester.edu"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.9.0-alpha.1"
indexmap = "2.2.6"